# Generated by Django 5.2.4 on 2025-07-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=250)),
                ('company_ntn_cnic', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('sandbox_api', models.CharField(blank=True, max_length=250, null=True)),
                ('live_api', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=250)),
                ('company_ntn_cnic', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('register_type', models.CharField(choices=[('registered', 'Registered'), ('non-registered', 'Non Registered')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HScodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hs_code', models.CharField(max_length=100)),
                ('code_description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=250)),
                ('product_slug', models.CharField(max_length=250, unique=True)),
                ('hs_code', models.CharField(max_length=100)),
                ('measurment_unit', models.CharField(max_length=100)),
                ('hs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.hscodemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
