# Generated by Django 5.2.4 on 2025-07-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='province',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('KPK', 'KPK'), ('Sindh', 'Sindh'), ('Balochistan', 'Balochistan'), ('AJK & GB', 'AJK & GB')], max_length=50),
        ),
    ]
