# Generated by Django 5.2.4 on 2025-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customermodel_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscodemodel',
            name='hs_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
