# Generated by Django 5.2.4 on 2025-07-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hscodemodel_hs_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='hs_code',
        ),
    ]
