# Generated by Django 5.2.4 on 2025-07-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_itemmodel_hs_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='hs_id',
            new_name='hs_code',
        ),
    ]
