# Generated by Django 5.2.4 on 2025-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_measurmentunitmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurmentunitmodel',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
