# Generated by Django 5.2.4 on 2025-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_measurmentunitmodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
