# Generated by Django 5.2.4 on 2025-07-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_scenariomodel_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='measurment_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.measurmentunitmodel'),
        ),
    ]
