# Generated by Django 5.2.4 on 2025-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_itemmodel_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoiceRefNo', models.CharField(max_length=50, unique=True)),
                ('invoiceDate', models.DateField()),
                ('invoiceType', models.CharField(max_length=250)),
                ('fbrInvoiceNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='home.companymodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='home.customermodel')),
                ('scenarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='home.scenariomodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_message', models.TextField()),
                ('log_type', models.CharField(blank=True, default='info', max_length=50, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.invoicemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('totalValues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valueSalesExcludingST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salesTaxApplicable', models.IntegerField()),
                ('salesTaxWithheldAtSource', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sroScheduleNo', models.CharField(blank=True, max_length=150, null=True)),
                ('sroItemSerialNo', models.CharField(blank=True, max_length=150, null=True)),
                ('furtherTax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fedPayable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saleType', models.CharField(max_length=50)),
                ('extraTax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fbrInvoiceNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='home.itemmodel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.invoicemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
