# Generated by Django 5.2.4 on 2025-08-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_invoicemodel_invoicelogmodel_invoiceitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
