# Generated by Django 5.2.4 on 2025-08-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_invoicemodel_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='register_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Non Registered', 'Non Registered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicelogmodel',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='home.invoicemodel'),
        ),
    ]
