# Generated by Django 5.2.4 on 2025-08-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_customermodel_register_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='home.companymodel'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='home.customermodel'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='scenarioId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='home.scenariomodel'),
        ),
    ]
