# Generated by Django 5.2.4 on 2025-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_invoicemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='fbr_integrate',
            field=models.BooleanField(default=False),
        ),
    ]
