# Generated by Django 5.2.4 on 2025-08-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_invoicemodel_fbr_integrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
