# Generated by Django 5.2.4 on 2025-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_companymodel_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='with_holding_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
