# Generated by Django 5.2.4 on 2025-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_licensemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensemodel',
            name='license_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
