# Generated by Django 6.0.3 on 2026-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_licensemodel_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='register_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='salesTaxApplicable',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
