# Generated by Django 6.0.3 on 2026-04-02 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_customermodel_register_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitemmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='hs_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='product_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='product_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='uom',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
