# Generated by Django 6.0.3 on 2026-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_invoiceitemmodel_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='extraTax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='fedPayable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='furtherTax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='salesTaxApplicable',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='salesTaxWithheldAtSource',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='totalValues',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitemmodel',
            name='valueSalesExcludingST',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
